export declare const isUndefined: (obj: any) => obj is undefined;
export declare const isFunction: (fn: any) => boolean;
export declare const isObject: (fn: any) => fn is object;
export declare const isString: (fn: any) => fn is string;
export declare const isConstructor: (fn: any) => boolean;
export declare const validatePath: (path: any) => string;
export declare const isNil: (obj: any) => boolean;
export declare const isEmpty: (array: any) => boolean;
export declare const isSymbol: (fn: any) => boolean;
