"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TCP_DEFAULT_PORT = 3000;
exports.TCP_DEFAULT_HOST = 'localhost';
exports.REDIS_DEFAULT_URL = 'redis://localhost:6379';
exports.CONNECT_EVENT = 'connect';
exports.MESSAGE_EVENT = 'message';
exports.ERROR_EVENT = 'error';
exports.CLOSE_EVENT = 'close';
exports.PATTERN_METADATA = 'pattern';
exports.CLIENT_CONFIGURATION_METADATA = 'client';
exports.CLIENT_METADATA = '__isClient';
exports.PATTERN_HANDLER_METADATA = '__isPattern';
exports.NO_PATTERN_MESSAGE = `There's no equivalent message pattern.`;
