import { MigrationInterface, QueryRunner } from 'typeorm';

export class Outbox1790154527507 implements MigrationInterface {
  name = 'Outbox1790154527507';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            CREATE TABLE "outbox_messages" (
                "seq" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "id" text NOT NULL,
                "topic" text NOT NULL,
                "payload" jsonb,
                "headers" jsonb NOT NULL,
                "key" text,
                "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
                "available_at" TIMESTAMP WITH TIME ZONE NOT NULL,
                "attempts" integer NOT NULL DEFAULT '0',
                "last_error" text,
                "history" jsonb NOT NULL DEFAULT '[]',
                "lease_owner" text,
                "lease_until" TIMESTAMP WITH TIME ZONE,
                CONSTRAINT "UQ_0171348f527c64b137e4d4f5b66" UNIQUE ("id"),
                CONSTRAINT "PK_d24ca6550fc486f101fe4f8b021" PRIMARY KEY ("seq")
            )
        `);
    await queryRunner.query(`
            CREATE INDEX "outbox_messages_key_seq" ON "outbox_messages" ("key", "seq")
        `);
    await queryRunner.query(`
            CREATE TABLE "outbox_dead_letters" (
                "id" text NOT NULL,
                "seq" bigint NOT NULL,
                "topic" text NOT NULL,
                "payload" jsonb,
                "headers" jsonb NOT NULL,
                "key" text,
                "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
                "attempts" integer NOT NULL,
                "last_error" text,
                "history" jsonb NOT NULL,
                "reason" text NOT NULL,
                "failed_at" TIMESTAMP WITH TIME ZONE NOT NULL,
                CONSTRAINT "PK_865626cb0b65e2889216c075044" PRIMARY KEY ("id")
            )
        `);
    await queryRunner.query(`
            CREATE INDEX "outbox_dead_letters_topic_failed_at" ON "outbox_dead_letters" ("topic", "failed_at")
        `);
    await queryRunner.query(`
            CREATE TABLE "outbox_inbox" (
                "consumer" text NOT NULL,
                "message_id" text NOT NULL,
                "processed_at" TIMESTAMP WITH TIME ZONE NOT NULL,
                CONSTRAINT "PK_c0e4a67e4a7ed5e6890bbfc682e" PRIMARY KEY ("consumer", "message_id")
            )
        `);
    await queryRunner.query(`
            CREATE INDEX "outbox_inbox_processed_at" ON "outbox_inbox" ("processed_at")
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            DROP INDEX "public"."outbox_inbox_processed_at"
        `);
    await queryRunner.query(`
            DROP TABLE "outbox_inbox"
        `);
    await queryRunner.query(`
            DROP INDEX "public"."outbox_dead_letters_topic_failed_at"
        `);
    await queryRunner.query(`
            DROP TABLE "outbox_dead_letters"
        `);
    await queryRunner.query(`
            DROP INDEX "public"."outbox_messages_key_seq"
        `);
    await queryRunner.query(`
            DROP TABLE "outbox_messages"
        `);
  }
}
