CREATE TABLE "outbox_dead_letters" (
	"id" text PRIMARY KEY NOT NULL,
	"seq" bigint NOT NULL,
	"topic" text NOT NULL,
	"payload" jsonb,
	"headers" jsonb NOT NULL,
	"key" text,
	"created_at" timestamp with time zone NOT NULL,
	"attempts" integer NOT NULL,
	"last_error" text,
	"history" jsonb NOT NULL,
	"reason" text NOT NULL,
	"failed_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "outbox_inbox" (
	"consumer" text NOT NULL,
	"message_id" text NOT NULL,
	"processed_at" timestamp with time zone NOT NULL,
	CONSTRAINT "outbox_inbox_consumer_message_id_pk" PRIMARY KEY("consumer","message_id")
);
--> statement-breakpoint
CREATE TABLE "outbox_messages" (
	"seq" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "outbox_messages_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text NOT NULL,
	"topic" text NOT NULL,
	"payload" jsonb,
	"headers" jsonb NOT NULL,
	"key" text,
	"created_at" timestamp with time zone NOT NULL,
	"available_at" timestamp with time zone NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	"history" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"lease_owner" text,
	"lease_until" timestamp with time zone,
	CONSTRAINT "outbox_messages_id_unique" UNIQUE("id")
);
--> statement-breakpoint
CREATE INDEX "outbox_dead_letters_topic_failed_at" ON "outbox_dead_letters" USING btree ("topic","failed_at");--> statement-breakpoint
CREATE INDEX "outbox_inbox_processed_at" ON "outbox_inbox" USING btree ("processed_at");--> statement-breakpoint
CREATE INDEX "outbox_messages_key_seq" ON "outbox_messages" USING btree ("key","seq");